version: '3'
services:
  web:
    env_file: ./.env
    networks: 
      - app_net 
    build: 
      context: ./configuration/nginx
      dockerfile: Dockerfile
      args:
        NGINX_VERSION: ${NGINX_VERSION}
    environment: 
      HOST_USER_UID: ${HOST_USER_UID}
      HOST_USER_GID: ${HOST_USER_GID}
    ports:
      - "${NGINX_PORT}:80"
    restart: ${RESTART}
    volumes:
      - './code:/code:cached'
      - "${NGINX_VHOST_DIR}:/etc/nginx/conf.d/"
      - './configuration/nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './logs/nginx:/var/log/nginx'
  mysql:
    env_file: ./.env
    networks:
      - app_net
    build: 
      dockerfile: Dockerfile
      context: ./configuration/mysql
      args:
        MYSQL_VERSION: ${MYSQL_VERSION}
    volumes:
      - './data/mysql:/var/lib/mysql'
      - './shared:/shared'
    restart: ${RESTART}
    environment: 
      MYSQL_VERSION: ${MYSQL_VERSION}
      HOST_USER_UID: ${HOST_USER_UID}
      HOST_USER_GID: ${HOST_USER_GID}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
  php7:
    env_file: ./.env
    networks:
      - app_net
    build: 
      context: ./configuration/php/php7
      dockerfile: Dockerfile
      args: 
        PHP7_VERSION: ${PHP7_VERSION}
    environment:
      HOST_USER_UID: ${HOST_USER_UID}
      HOST_USER_GID: ${HOST_USER_GID}
    expose:
      - '9002'
    restart: ${RESTART}
    volumes:
      - './code:/code:cached'
      - './configuration/php/www.conf:/usr/local/etc/php-fpm.d/zz-docker.conf'
      - './configuration/php/php7/fpm.conf:/usr/local/etc/php-fpm.conf'
      - './configuration/php/php7/ext:/usr/local/etc/php/conf.d'
      - './configuration/php/php7/php.ini:/usr/local/etc/php/php.ini'
    working_dir: /code

  redis:
    image: "redis:alpine"
    networks:
      - app_net
    restart: ${RESTART}
    ports:
      - "${REDIS_PORT}:6379"
  rabbitmq:
    networks:
      - app_net
    image: rabbitmq:${RABBITMQ_VERSION}
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: user
    ports:
      - "${RABBITMQ_PORT}:15672"
    restart: ${RESTART}
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
          #gateway: 10.0.0.1
